# These are supported funding model platforms

github: # Replace with your GitHub username(s)
patreon: # Replace with Patreon username
open_collective: # Replace with Open Collective username
ko_fi: # Replace with Ko-fi username
custom: # Add your custom sponsorship URL(s)
